package com.java.NaniYiMiDa.enumx;

public enum AllergenEnum {
    MILK("牛奶"),
    EGG("鸡蛋"),
    FISH("鱼"),
    CRUSTACEAN_SHELLFISH("甲壳类海鲜"),
    TREE_NUTS("树坚果"),
    PEANUTS("花生"),
    WHEAT("小麦"),
    SOY("大豆"),
    SESAME("芝麻"),
    MUSTARD("芥末"),
    CELERY("芹菜"),
    SULPHUR_DIOXIDE("硫磺二氧化物"),
    LUPIN("羽扇豆"),
    MOLLUSCS("软体动物"),
    CORN("玉米"),
    GLUTEN("麸质"),
    SHELLFISH("贝类"),
    ALMONDS("杏仁"),
    WALNUTS("核桃"),
    CASHEWS("腰果"),
    PISTACHIOS("开心果"),
    HAZELNUTS("榛子"),
    PECANS("山核桃"),
    BRAZIL_NUTS("巴西坚果"),
    MACADAMIA_NUTS("澳洲坚果"),
    PINE_NUTS("松子"),
    CHESTNUTS("栗子"),
    COCONUT("椰子"),
    DAIRY("乳制品"),
    MEAT("肉类"),
    POULTRY("家禽"),
    PORK("猪肉"),
    BEEF("牛肉"),
    LAMB("羊肉"),
    SEAFOOD("海鲜"),
    CRAB("蟹"),
    LOBSTER("龙虾"),
    SHRIMP("虾"),
    CLAMS("蛤蜊"),
    OYSTERS("牡蛎"),
    SCALLOPS("扇贝"),
    SQUID("鱿鱼"),
    OCTOPUS("章鱼"),
    FRUITS("水果"),
    CITRUS("柑橘类"),
    APPLES("苹果"),
    PEARS("梨"),
    PEACHES("桃"),
    PLUMS("李子"),
    CHERRIES("樱桃"),
    BERRIES("浆果"),
    STRAWBERRIES("草莓"),
    BLUEBERRIES("蓝莓"),
    RASPBERRIES("树莓"),
    BLACKBERRIES("黑莓"),
    VEGETABLES("蔬菜"),
    TOMATOES("番茄"),
    POTATOES("土豆"),
    CARROTS("胡萝卜"),
    ONIONS("洋葱"),
    GARLIC("大蒜"),
    PEPPERS("辣椒"),
    SPICES("香料"),
    CINNAMON("肉桂"),
    PAPRIKA("辣椒粉"),
    CUMIN("孜然"),
    CORIANDER("香菜"),
    TURMERIC("姜黄"),
    GINGER("姜"),
    PEPPER("胡椒"),
    CLOVES("丁香"),
    NUTMEG("肉豆蔻"),
    CARDAMOM("豆蔻"),
    SAFFRON("藏红花"),
    VANILLA("香草"),
    CHOCOLATE("巧克力"),
    COFFEE("咖啡"),
    TEA("茶"),
    ALCOHOL("酒精"),
    YEAST("酵母"),
    MOLD("霉菌");

    private final String description;

    AllergenEnum(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}
