package com.java.NaniYiMiDa.enumx;

public enum ProductIngredientEnum {
    // 蔬菜
    TOMATO("番茄"),
    ONION("洋葱"),
    GARLIC("大蒜"),
    CARROT("胡萝卜"),
    POTATO("土豆"),
    BROCCOLI("西兰花"),
    SPINACH("菠菜"),
    LETTUCE("生菜"),
    CUCUMBER("黄瓜"),
    BELL_PEPPER("彩椒"),
    MUSHROOM("蘑菇"),
    CORN("玉米"),
    BEANS("豆类"),
    GREEN_BEANS("青豆"),
    PEAS("豌豆"),
    CABBAGE("卷心菜"),
    CAULIFLOWER("花椰菜"),
    ZUCCHINI("西葫芦"),
    EGGPLANT("茄子"),
    RADISH("萝卜"),
    BEET("甜菜"),
    CELERY("芹菜"),
    PARSLEY("欧芹"),
    CILANTRO("香菜"),
    BASIL("罗勒"),
    THYME("百里香"),
    ROSEMARY("迷迭香"),
    SAGE("鼠尾草"),
    OREGANO("牛至"),
    DILL("莳萝"),

    // 水果
    APPLE("苹果"),
    BANANA("香蕉"),
    ORANGE("橙子"),
    LEMON("柠檬"),
    LIME("青柠"),
    GRAPEFRUIT("葡萄柚"),
    STRAWBERRY("草莓"),
    BLUEBERRY("蓝莓"),
    RASPBERRY("树莓"),
    BLACKBERRY("黑莓"),
    PEACH("桃"),
    PLUM("李子"),
    CHERRY("樱桃"),
    PEAR("梨"),
    PINEAPPLE("菠萝"),
    MANGO("芒果"),
    KIWI("猕猴桃"),
    WATERMELON("西瓜"),
    CANTALOUPE("哈密瓜"),
    HONEYDEW("蜜瓜"),
    GRAPES("葡萄"),
    AVOCADO("鳄梨"),

    // 肉类和海鲜
    CHICKEN("鸡肉"),
    BEEF("牛肉"),
    PORK("猪肉"),
    LAMB("羊肉"),
    TURKEY("火鸡"),
    FISH("鱼"),
    SALMON("三文鱼"),
    TUNA("金枪鱼"),
    COD("鳕鱼"),
    SHRIMP("虾"),
    CRAB("蟹"),
    LOBSTER("龙虾"),
    CLAMS("蛤蜊"),
    OYSTERS("牡蛎"),
    SCALLOPS("扇贝"),
    SQUID("鱿鱼"),
    OCTOPUS("章鱼"),

    // 谷物和谷物制品
    RICE("大米"),
    WHEAT("小麦"),
    OATS("燕麦"),
    BARLEY("大麦"),
    QUINOA("藜麦"),
    BUCKWHEAT("荞麦"),
    MILLET("小米"),
    SORGHUM("高粱"),
    RYE("黑麦"),
    CORNMEAL("玉米粉"),
    FLOUR("面粉"),
    BREAD("面包"),
    PASTA("意大利面"),
    NOODLES("面条"),

    // 乳制品
    MILK("牛奶"),
    CHEESE("奶酪"),
    BUTTER("黄油"),
    YOGURT("酸奶"),
    CREAM("奶油"),
    SOUR_CREAM("酸奶油"),
    COTTAGE_CHEESE("农家奶酪"),

    // 鸡蛋和家禽制品
    EGG("鸡蛋"),
    EGG_WHITE("蛋白"),
    EGG_YOLK("蛋黄"),

    // 坚果和种子
    ALMONDS("杏仁"),
    WALNUTS("核桃"),
    PEANUTS("花生"),
    CASHEWS("腰果"),
    PISTACHIOS("开心果"),
    HAZELNUTS("榛子"),
    PECANS("山核桃"),
    BRAZIL_NUTS("巴西坚果"),
    MACADAMIA_NUTS("澳洲坚果"),
    PINE_NUTS("松子"),
    CHESTNUTS("栗子"),
    SESAME_SEEDS("芝麻"),
    SUNFLOWER_SEEDS("葵花籽"),
    PUMPKIN_SEEDS("南瓜籽"),
    FLAXSEEDS("亚麻籽"),
    CHIA_SEEDS("奇亚籽"),

    // 调味品和调料
    SALT("盐"),
    PEPPER("胡椒"),
    SUGAR("糖"),
    BROWN_SUGAR("红糖"),
    HONEY("蜂蜜"),
    MAPLE_SYRUP("枫糖浆"),
    VINEGAR("醋"),
    SOY_SAUCE("酱油"),
    WORCESTERSHIRE_SAUCE("伍斯特酱"),
    MUSTARD("芥末"),
    MAYONNAISE("蛋黄酱"),
    KETCHUP("番茄酱"),
    OLIVE_OIL("橄榄油"),
    VEGETABLE_OIL("植物油"),
    COCONUT_OIL("椰子油"),
    BUTTER_OIL("黄油油"),

    // 香料
    GINGER("姜"),
    CINNAMON("肉桂"),
    CUMIN("孜然"),
    CORIANDER("香菜种子"),
    TURMERIC("姜黄"),
    PAPRIKA("辣椒粉"),
    CAYENNE("卡宴辣椒"),
    CHILI_POWDER("辣椒粉"),
    NUTMEG("肉豆蔻"),
    CLOVES("丁香"),
    CARDAMOM("豆蔻"),
    SAFFRON("藏红花"),
    VANILLA("香草"),
    ANISE("茴香"),
    FENNEL("茴香"),
    STAR_ANISE("八角"),

    // 其他
    YEAST("酵母"),
    BAKING_POWDER("发酵粉"),
    BAKING_SODA("小苏打"),
    COCOA("可可"),
    CHOCOLATE("巧克力"),
    COFFEE("咖啡"),
    TEA("茶"),
    GELATIN("明胶"),
    AGAR_AGAR("琼脂"),
    SOYBEAN("大豆"),
    TOFU("豆腐"),
    TEMPEH("天贝"),
    SEITAN("面筋");

    private final String description;

    ProductIngredientEnum(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}
